.PHONY: all, clean, build, deploy, local

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo " install		to install npm packages"
	@echo " local		to run local server"

install:
	npm install

local:
	npm run dev